@echo off
REM ═══════════════════════════════════════════════════════════════
REM  VURA Installer for Windows — One-Time Setup
REM ═══════════════════════════════════════════════════════════════
REM  Installs dependencies, creates a global 'vura' command,
REM  and sets up the project so you can run it from anywhere.
REM
REM  Usage:  install.bat    (double-click or run from cmd)
REM ═══════════════════════════════════════════════════════════════

setlocal EnableDelayedExpansion

echo.
echo  ======================================
echo   VURA Installer — v1.0.0
echo   Vulnerability Reporting AI
echo  ======================================
echo.

REM ── Step 1: Check Python ─────────────────────────────────────
echo [1/5] Checking Python installation...
python --version >nul 2>&1
if errorlevel 1 (
    python3 --version >nul 2>&1
    if errorlevel 1 (
        echo   [X] Python 3 not found. Please install Python 3.10+ from https://python.org
        echo       Make sure to check "Add Python to PATH" during installation.
        pause
        exit /b 1
    )
    set PY=python3
) else (
    set PY=python
)
for /f "tokens=*" %%i in ('%PY% --version 2^>^&1') do set PY_VER=%%i
echo   [OK] Found: %PY_VER%

REM ── Step 2: Create virtual environment ───────────────────────
echo.
echo [2/5] Setting up virtual environment...
if not exist "%~dp0.venv" (
    %PY% -m venv "%~dp0.venv"
    echo   [OK] Created .venv
) else (
    echo   [OK] .venv already exists
)

REM Activate venv for this session
call "%~dp0.venv\Scripts\activate.bat"

REM ── Step 3: Install dependencies ─────────────────────────────
echo.
echo [3/5] Installing Python dependencies...
pip install --quiet --upgrade pip 2>nul
if exist "%~dp0requirements.txt" (
    pip install --quiet -r "%~dp0requirements.txt"
    echo   [OK] Core dependencies installed
) else (
    echo   [X] requirements.txt not found!
    pause
    exit /b 1
)
echo   Installing Flet GUI framework...
pip install --quiet flet
echo   [OK] Flet installed

REM ── Step 4: Create config.json if missing ────────────────────
echo.
echo [4/5] Checking configuration...
if not exist "%~dp0config.json" (
    copy "%~dp0config.example.json" "%~dp0config.json" >nul
    echo   [OK] Created config.json from template
    echo        Run 'vura -Ch' after installation to set your API keys.
) else (
    echo   [OK] config.json already exists
)

REM Ensure directories exist
if not exist "%~dp0data" mkdir "%~dp0data"
if not exist "%~dp0reports\md" mkdir "%~dp0reports\md"
if not exist "%~dp0reports\json" mkdir "%~dp0reports\json"
if not exist "%~dp0reports\pdf" mkdir "%~dp0reports\pdf"
if not exist "%~dp0reports\docx" mkdir "%~dp0reports\docx"
if not exist "%~dp0reports\sh" mkdir "%~dp0reports\sh"

REM ── Step 5: Create global 'vura' command ─────────────────────
echo.
echo [5/5] Creating global 'vura' command...

set "VURA_HOME=%~dp0"
set "WRAPPER=%~dp0vura.bat"

REM Create the wrapper batch file
(
    echo @echo off
    echo REM VURA — Global Launcher (auto-generated by install.bat^)
    echo REM Launches GUI (no args^) or CLI (with args^).
    echo call "%VURA_HOME%.venv\Scripts\activate.bat"
    echo if "%%~1"=="" (
    echo     python "%VURA_HOME%gui.py" %%*
    echo ^) else (
    echo     python "%VURA_HOME%main.py" %%*
    echo ^)
) > "%WRAPPER%"

REM Add project directory to user PATH if not already there
echo %PATH% | find /i "%VURA_HOME%" >nul
if errorlevel 1 (
    setx PATH "%PATH%;%VURA_HOME%" >nul 2>&1
    echo   [OK] Added %VURA_HOME% to your PATH
    echo        Please restart your terminal for PATH changes to take effect.
) else (
    echo   [OK] Project directory already in PATH
)

echo   [OK] Created vura.bat wrapper

REM ── Done ─────────────────────────────────────────────────────
echo.
echo  ══════════════════════════════════════════════════════
echo.
echo   [OK] VURA is successfully installed!
echo.
echo   Just type 'vura' to launch the GUI.
echo   Type 'vura -h' for CLI commands.
echo.
echo   First time? Run 'vura -Ch' to configure your AI key.
echo.
echo  ══════════════════════════════════════════════════════
echo.
pause
