#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# VURA Installer — One-Time Setup
# ═══════════════════════════════════════════════════════════════
# Installs dependencies, creates a global 'vura' command,
# and sets up the project so you can run it from anywhere.
#
# Usage:  bash install.sh
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────
GREEN='\033[1;32m'
CYAN='\033[1;36m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
DIM='\033[2m'
RESET='\033[0m'

# ── Resolve project root (where this script lives) ─────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo ""
echo -e "${CYAN}╔══════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║   🛡️  VURA Installer — v1.0.0            ║${RESET}"
echo -e "${CYAN}║   Vulnerability Reporting AI             ║${RESET}"
echo -e "${CYAN}╚══════════════════════════════════════════╝${RESET}"
echo ""

# ── Step 1: Check Python ───────────────────────────────────────
echo -e "${YELLOW}[1/4]${RESET} Checking Python installation..."
if command -v python3 &>/dev/null; then
    PY="python3"
    PY_VER=$($PY --version 2>&1)
    echo -e "  ${GREEN}✔${RESET} Found: ${PY_VER}"
else
    echo -e "  ${RED}✘ Python 3 not found. Please install Python 3.10+ first.${RESET}"
    exit 1
fi

# ── Step 2: Install pip dependencies (venv to avoid PEP 668) ──
echo ""
echo -e "${YELLOW}[2/4]${RESET} Installing Python dependencies..."
if [ ! -f "${SCRIPT_DIR}/requirements.txt" ]; then
    echo -e "  ${RED}✘ requirements.txt not found in ${SCRIPT_DIR}${RESET}"
    exit 1
fi

VENV_DIR="${SCRIPT_DIR}/Venv"
if [ ! -d "${VENV_DIR}" ]; then
    echo -e "  ${DIM}Creating virtualenv at ${VENV_DIR}...${RESET}"
    $PY -m venv "${VENV_DIR}"
fi

VENV_PY="${VENV_DIR}/bin/python"
"${VENV_PY}" -m pip install --quiet --upgrade pip 2>/dev/null || true
"${VENV_PY}" -m pip install --quiet -r "${SCRIPT_DIR}/requirements.txt"
echo -e "  ${GREEN}✔${RESET} Dependencies installed into venv"

# ── Step 3: Create config.json if missing ─────────────────────
echo ""
echo -e "${YELLOW}[3/4]${RESET} Checking configuration..."
if [ ! -f "${SCRIPT_DIR}/config.json" ]; then
    cp "${SCRIPT_DIR}/config.example.json" "${SCRIPT_DIR}/config.json"
    chmod 600 "${SCRIPT_DIR}/config.json"
    echo -e "  ${GREEN}✔${RESET} Created config.json from template"
    echo -e "  ${DIM}Run 'vura -Ch' after installation to set your API keys.${RESET}"
else
    echo -e "  ${GREEN}✔${RESET} config.json already exists"
fi

# Ensure data & reports directories exist
mkdir -p "${SCRIPT_DIR}/data"
mkdir -p "${SCRIPT_DIR}/reports"/{md,json,pdf,docx,sh}

# ── Step 4: Create global 'vura' command ──────────────────────
echo ""
echo -e "${YELLOW}[4/4]${RESET} Creating global 'vura' command..."

WRAPPER_CONTENT="#!/usr/bin/env bash
# VURA — Global Launcher (auto-generated by install.sh)
# Launches CLI (with args) or GUI (without args).
VURA_HOME=\"${SCRIPT_DIR}\"
VURA_PY=\"\${VURA_HOME}/Venv/bin/python\"
# Fall back to system python3 if the venv was removed.
if [ ! -x \"\${VURA_PY}\" ]; then
    VURA_PY=\"\$(command -v python3)\"
fi

if [ \$# -eq 0 ]; then
    # No arguments → launch GUI
    exec \"\${VURA_PY}\" \"\${VURA_HOME}/gui.py\" \"\$@\"
else
    # With arguments → launch CLI
    exec \"\${VURA_PY}\" \"\${VURA_HOME}/main.py\" \"\$@\"
fi
"

# Determine install path
INSTALL_DIR="/usr/local/bin"
INSTALL_PATH="${INSTALL_DIR}/vura"

# Check if we can write to /usr/local/bin
if [ -w "$INSTALL_DIR" ]; then
    echo "$WRAPPER_CONTENT" > "$INSTALL_PATH"
    chmod +x "$INSTALL_PATH"
    echo -e "  ${GREEN}✔${RESET} Installed to ${INSTALL_PATH}"
else
    echo -e "  ${DIM}Requires sudo to write to ${INSTALL_DIR}${RESET}"
    echo "$WRAPPER_CONTENT" | sudo tee "$INSTALL_PATH" > /dev/null
    sudo chmod +x "$INSTALL_PATH"
    echo -e "  ${GREEN}✔${RESET} Installed to ${INSTALL_PATH} (with sudo)"
fi

# ── Done ──────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}║                                                          ║${RESET}"
echo -e "${GREEN}║   ✅  VURA is successfully installed!                    ║${RESET}"
echo -e "${GREEN}║                                                          ║${RESET}"
echo -e "${GREEN}║   Just type ${CYAN}vura${GREEN} to launch the GUI.                    ║${RESET}"
echo -e "${GREEN}║   Type ${CYAN}vura -h${GREEN} for CLI commands.                       ║${RESET}"
echo -e "${GREEN}║                                                          ║${RESET}"
echo -e "${GREEN}║   First time? Run ${CYAN}vura -Ch${GREEN} to configure your AI key.   ║${RESET}"
echo -e "${GREEN}║                                                          ║${RESET}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${RESET}"
echo ""
